### ISSUE TITLE
怎样知道爬取完成了呢

### ISSUE THREAD

**Issue by vanichocola** [hupo376787/WeiboAlbumDownloader#2]
如题，遇到较多微博内容的微博难以找到最初的微博，故无法人为判断最早的微博是什么时候的，以下是爬取了一定量的内容后出现的报错。

遇到错误System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Convert.ToInt32(String value)
   at WeiboAlbumDownloader.MainWindow.<Start>b__15_0() in D:\GitHub\WeiboAlbumDownloader\WeiboAlbumDownloader\MainWindow.xaml.cs:line 351
   at WeiboAlbumDownloader.MainWindow.Start() in D:\GitHub\WeiboAlbumDownloader\WeiboAlbumDownloader\MainWindow.xaml.cs:line 87，请稍后重试。

**Comment by hupo376787** [comment]
com的时候，是根据返回来的json数据，看下一页的图片列表是否空，为空表示完成。
cn的时候，是根据页面返回的html，里面有一个节点是微博的页数。页数循环结束就是完成。

根据你的错误信息，貌似是解析html的时候，字段出错了。
