### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by hctjtb** [hupo376787/WeiboAlbumDownloader#6]
**Bug描述**
下载过程中断，错误提示：
遇到错误，uid: 7040041221，DataSource: WeiboCn，Page:148，SinceId: 4431289194689067，System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Convert.ToInt32(String value)
   at WeiboAlbumDownloader.MainWindow.<>c__DisplayClass15_0.<<Start>b__0>d.MoveNext() in D:\GitHub\WeiboAlbumDownloader\WeiboAlbumDownloader\MainWindow.xaml.cs:line 490
--- End of stack trace from previous location ---
   at WeiboAlbumDownloader.MainWindow.Start(String userId) in D:\GitHub\WeiboAlbumDownloader\WeiboAlbumDownloader\MainWindow.xaml.cs:line 132，请稍后重试。

**Comment by hupo376787** [comment]
我今天试一下，看错误信息应该是一个数值转换错误，导致解析出错了

**Comment by hupo376787** [comment]
我试了一下，没有复现，可以完整下载下来。你再试一下
